apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: appointments:latest # docker build -t appointments:latest mfe-appointments/
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  selector:
    app: appointments
  ports:
  - port: 80
    targetPort: 80
